### ISSUE TITLE
The List is not updated to the the new domains

### ISSUE THREAD

**Issue by 0akz06** [prorounak2005/Blacklist-for-fake-anime-websites#1]
Hi Disguised

**Comment by prorounak2005** [comment]
Hi @0akz06 actually I am not active in this project rn. I will definetly give a look to it when I am free and I will update the blocklist.

**Comment by 0akz** [comment]
alright friend i want to fork it

**Comment by prorounak2005** [comment]
> alright friend i want to fork it

Ofc you can if you want :)
